baseURL = "https://robamu.github.io"
languageCode = 'en-us'
title = 'hi, I am robin'
theme = "PaperMod"
disqusShortname = "https-robamu-github-io"

pygmentsStyle = "pygments"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

enableGitInfo = true
mainSections = "main"
# sectionPagesMenu = 'main'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  title = "robins website"
  keyword = "coding, rust, c++, python, aerospace, satellites"
  commit = false
  comments = true
  goatcounter = "robamu"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowWordCount = false
  ShowPageViews = true
  ShowCodeCopyButtons = true
  socialShare = true
  showRelatedPosts = true
  # Google Programmable Search Engine
  gcse = "49f27010d1fda4554"
  # Footer section
  [params.footer]
    enable = true

[params.author]
name = "Robin Mueller"
github = "robamu"
linkedin = "robin-mueller-m"

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
name = "sat-rs book"
url = "/sat-rs/book/"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5
